name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery
