name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: swift build
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    - name: Run tests
      run: swift test
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
